### ISSUE TITLE
Build Failure due to : unknown property 'archiveBaseVersion' for task ':jar'

### ISSUE THREAD

**Issue by gauravghongde** [geektrust/coding-problem-artefacts#4]
https://github.com/geektrust/coding-problem-artefacts/blob/0763458caefbed7352b892d675cd39c8e8d0294b/Java/build.gradle#L14

getting following error for the boilerplate code for Gradle version
` Could not set unknown property 'archiveBaseVersion' for task ':jar' of type org.gradle.api.tasks.bundling.Jar.`

Full stack 
```
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'MeetTheFamily'.
Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'archiveBaseVersion' for task ':jar' of type org.gradle.api.tasks.bundling.Jar.
	at org.gradle.internal.metaobject.AbstractDynamicObject.setMissingProperty(AbstractDynamicObject.java:117)
	at org.gradle.internal.metaobject.ConfigureDelegate.setProperty(ConfigureDelegate.java:104)
```

Gradle version 
```
Gradle 6.4.1
------------------------------------------------------------

Build time:   2020-05-15 19:43:40 UTC
Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5

Kotlin:       1.3.71
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_251 (Oracle Corporation 25.251-b08)
OS:           Windows 10 10.0 amd64

```

**Comment by gauravghongde** [comment]
My Bad, seems like there is already a new fixed build.gradle present
https://github.com/geektrust/coding-problem-artefacts/blob/master/build-files/java/build.gradle
